### ISSUE TITLE
Need to custom size

### ISSUE THREAD

**Issue by SavantEVO** [mkdocs-plugins/termynal#19]
Hello ! Please help me ! How to config  resize bash . Thank you !
![image](https://github.com/mkdocs-plugins/termynal/assets/109493900/a7ae7def-b54b-4941-b6a1-1f203e1bf60f)

**Comment by daxartio** [comment]
Hello!

Do you need to resize of each block?

**Comment by daxartio** [comment]
You can do it like this

```css
[data-termynal] {
    max-width: 100%;
}
```
