### ISSUE TITLE
multi-line command issue and minify plugin

### ISSUE THREAD

**Issue by carried-away** [mkdocs-plugins/termynal#21]
Hello,

I'm running into an issue with mutli-line commands. 

when i do 

```
> does this work \
  second command
output
```

i get the first two lines in one line

![image](https://github.com/mkdocs-plugins/termynal/assets/119022007/a642d150-d76c-479d-84ab-e5d065a54f91)

**Comment by carried-away** [comment]
I apologize for opening this issue.

I installed your amazing plugin in a different environment and found that it worked without issue.

The environment I initially ran into a problem was running the minify plugin. 

```yaml
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
```

I disabled that and was good to go. Sorry again and thank you for your work!
